name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          echo "REACT_APP_GROQ_API_KEY_1=${{ secrets.REACT_APP_GROQ_API_KEY_1 }}" > .env
          echo "REACT_APP_GROQ_API_KEY_2=${{ secrets.REACT_APP_GROQ_API_KEY_2 }}" >> .env
          echo "REACT_APP_GOOGLE_API_KEY=${{ secrets.REACT_APP_GOOGLE_API_KEY }}" >> .env
          echo "REACT_APP_GROQ_API_URL=${{ secrets.REACT_APP_GROQ_API_URL }}" >> .env
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true